/* Generated by cbindgen from the wxscan-ffi crate. Do not edit. */

#ifndef WXSCAN_H
#define WXSCAN_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Why [`wxscan_scan_path`] returned nothing.
 *
 * A scan that finds no symbol is [`WxScanStatus::Ok`] with an empty result
 * set, which is a different thing from a file that could not be read at all.
 * Collapsing the two is how a picture the library never even saw comes back
 * looking like a picture with no code in it.
 */
enum WxScanStatus
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * The file was read and scanned. The result set may still be empty.
   */
  Ok = 0,
  /**
   * A null pointer, a path that is not UTF-8, or a null scanner.
   */
  BadArgument = 1,
  /**
   * The path could not be opened or read.
   */
  Unreadable = 2,
  /**
   * The bytes were read but are not an image this build can decode. PNG,
   * JPEG and GIF are — the `image` dependency enables those three and no
   * others, because they are what a photo picker actually writes and the
   * rest cost 570 KB. HEIC is not, and nor is anything else needing a
   * system framework.
   *
   * A photo library is mostly HEIC, but a picker generally does not hand it
   * over that way: on iOS, `image_picker` sniffs the first byte, finds
   * neither JPEG nor PNG nor GIF, and re-encodes to JPEG on its way to disk.
   * The paths worth worrying about are the ones that come from somewhere
   * else — a file shared into the application, say — and a caller that has
   * to read those needs the platform's own decoder and
   * [`wxscan_scan_pixels`].
   */
  UnsupportedFormat = 3,
};
#ifndef __cplusplus
typedef int32_t WxScanStatus;
#endif // __cplusplus

/**
 * One decoded symbol.
 */
typedef struct WxScanResult {
  /**
   * Raw payload bytes, in the encoding named by `charset`.
   */
  const uint8_t *bytes;
  size_t bytes_len;
  /**
   * Payload decoded to UTF-8; GB2312 payloads are converted, everything else
   * is interpreted as UTF-8 with invalid sequences replaced.
   */
  const char *text;
  const char *charset;
  /**
   * Corner points in the upright frame, ordered top-left, top-right,
   * bottom-right, bottom-left, stored as `x0, y0, x1, y1, ...`.
   */
  float points[8];
  int32_t qrcode_version;
  const char *ec_level;
  const char *charset_mode;
  int32_t binary_method;
} WxScanResult;

/**
 * Result of scanning one frame.
 */
typedef struct WxScanResults {
  const struct WxScanResult *results;
  size_t results_len;
  /**
   * Detector candidates, 8 floats per quadrilateral in the same order as
   * [`WxScanResult::points`]. A non-empty candidate list with an empty
   * result list means a symbol was located but not decoded.
   */
  const float *candidates;
  /**
   * Number of quadrilaterals, not the number of floats.
   */
  size_t candidates_len;
  /**
   * Dimensions of the upright frame the coordinates refer to.
   */
  uint32_t width;
  uint32_t height;
} WxScanResults;

/**
 * A scanner handle.
 *
 * **Not a pointer.** It is a number this library hands out and looks up in a
 * table of its own, and that is the whole point: a handle that has been
 * released, or was never valid, or was invented by a caller, resolves to
 * nothing and comes back as an ordinary failure. Were it an address, each of
 * those would instead be a read of freed or arbitrary memory, crashing
 * somewhere with no trace of where the mistake was made.
 *
 * This matters because a scanner is routinely held by two sides at once that
 * cannot see each other's lifetimes: a managed application holding one for
 * still pictures while a camera binding, in another language, decodes frames
 * with the same handle. Reference counting alone ([`wxscan_scanner_retain`])
 * settles who frees it, but only a handle that is not an address makes a
 * stale one safe to present — and after a hot restart of the managed side,
 * stale handles are exactly what turns up.
 *
 * Zero is never a scanner. It means "none", and is what a failed
 * [`wxscan_scanner_new`] returns.
 *
 * Handles are never reused. A released number stays dead for the life of the
 * process, so a stale one can never come to name a different scanner — which
 * would put every one of the above problems back, silently.
 */
typedef size_t WxScanScannerId;

/**
 * A decoder the host lends to this library.
 *
 * Both function pointers are required; a struct with either missing is
 * rejected rather than half-installed.
 */
typedef struct WxScanImageDecoder {
  /**
   * Decode `data`, which is an encoded image file.
   *
   * Returns 1 on success, having written a pixel buffer and its shape
   * through the out parameters, and 0 for anything it does not recognise —
   * which is not an error, only an answer.
   *
   * `out_format` is a [`WxScanPixelFormat`]. Rows must be tightly packed.
   * The orientation recorded in the file is the host's to apply, since the
   * system decoders do it as a matter of course and this library cannot
   * tell whether it happened.
   */
  int32_t (*decode)(const uint8_t *data,
                    size_t len,
                    const uint8_t **out_pixels,
                    uint32_t *out_width,
                    uint32_t *out_height,
                    int32_t *out_format,
                    void *ctx);
  /**
   * Release a buffer a successful `decode` handed over. Called exactly once
   * per success, before the scan returns.
   */
  void (*release)(const uint8_t *pixels, void *ctx);
  /**
   * Passed back to both functions untouched.
   */
  void *ctx;
} WxScanImageDecoder;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Run detection and decoding on an upright, tightly packed grayscale image.
 *
 * Returns NULL if the scanner or the buffer is invalid; an empty result set
 * means nothing was found. The result must be released with
 * [`crate::results::wxscan_results_free`].
 *
 * # Safety
 * `data` must point to at least `width * height` readable bytes that stay
 * valid for the duration of the call.
 */
struct WxScanResults *wxscan_scan_gray(WxScanScannerId scanner,
                                       const uint8_t *data,
                                       int32_t width,
                                       int32_t height);

/**
 * Run detection and decoding on a colour image, converting it to grayscale
 * first.
 *
 * This exists so that a caller decoding a PNG or a JPEG does not have to
 * convert the pixels itself; the conversion here is the same one the algorithm
 * applies internally.
 *
 * `format` is a [`WxScanPixelFormat`]. Rows are tightly packed, so the buffer
 * must hold `width * height * bytes_per_pixel` bytes.
 *
 * Returns NULL on invalid input. The result must be released with
 * [`crate::results::wxscan_results_free`].
 *
 * # Safety
 * `data` must point to at least that many readable bytes, valid for the
 * duration of the call.
 */
struct WxScanResults *wxscan_scan_pixels(WxScanScannerId scanner,
                                         const uint8_t *data,
                                         int32_t width,
                                         int32_t height,
                                         int32_t format);

/**
 * Prepare a camera frame and scan it.
 *
 * * `row_stride` is the byte distance between rows of the Y plane and may
 *   exceed `width`.
 * * `rotation` is the clockwise angle in degrees needed to bring the frame
 *   upright.
 * * `mirror_output`, when non-zero, mirrors the returned x coordinates about
 *   the vertical axis of the upright frame. The frame itself is never
 *   mirrored: the CNN detector is trained on unmirrored input, so mirroring it
 *   lowers the detection rate. Use this when the preview is displayed
 *   mirrored, as front-facing camera previews usually are.
 *
 * Returns NULL on invalid input. The result must be released with
 * [`crate::results::wxscan_results_free`].
 *
 * # Safety
 * `data` must point to at least `row_stride * height` readable bytes that
 * stay valid for the duration of the call.
 */
struct WxScanResults *wxscan_scan_frame(WxScanScannerId scanner,
                                        const uint8_t *data,
                                        int32_t width,
                                        int32_t height,
                                        int32_t row_stride,
                                        int32_t rotation,
                                        int32_t mirror_output);

/**
 * Read an image file and scan it.
 *
 * This exists so that a caller holding a path does not have to decode the
 * picture itself and hand over the pixels: a 12 megapixel photograph is 48 MB
 * as RGBA, and a caller that crosses a thread or an isolate boundary pays for
 * that buffer more than once. Here the file is read, decoded and reduced to
 * grayscale without any of it crossing the boundary.
 *
 * `status`, when not NULL, is set to a [`WxScanStatus`] saying what happened.
 * Returns NULL for anything other than [`WxScanStatus::Ok`]. The result must
 * be released with [`crate::results::wxscan_results_free`].
 *
 * The orientation recorded in the file is applied, so a photograph taken with
 * the phone turned sideways is scanned upright and the coordinates come back
 * in the picture as it is meant to be seen.
 *
 * # Safety
 * `path` must be a NUL terminated string, and `status`, when not NULL, must point to a
 * writable [`WxScanStatus`].
 */
struct WxScanResults *wxscan_scan_path(WxScanScannerId scanner,
                                       const char *path,
                                       WxScanStatus *status);

/**
 * Decode an encoded image already in memory and scan it.
 *
 * The same work as [`wxscan_scan_path`] for a caller that has the bytes
 * rather than a path: an image picked from a photo library and handed over as
 * data, a download, an asset, or a browser, which has no filesystem to give a
 * path into at all.
 *
 * `data` is the *encoded* file — PNG, JPEG or GIF, the three this build
 * carries decoders for — not pixels. For pixels use [`wxscan_scan_pixels`].
 * The format is sniffed from the bytes, so no caller has to say which it is.
 *
 * `status`, when not NULL, is set to a [`WxScanStatus`] saying what happened.
 * [`WxScanStatus::Unreadable`] cannot arise here — there is nothing to open —
 * so a buffer that is not a picture this build decodes comes back as
 * [`WxScanStatus::UnsupportedFormat`]. Returns NULL for anything other than
 * [`WxScanStatus::Ok`]. The result must be released with
 * [`crate::results::wxscan_results_free`].
 *
 * The orientation recorded in the file is applied, exactly as for a path.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes that stay valid for the
 * duration of the call, and `status`, when not NULL, must point to a writable
 * [`WxScanStatus`].
 */
struct WxScanResults *wxscan_scan_bytes(WxScanScannerId scanner,
                                        const uint8_t *data,
                                        size_t len,
                                        WxScanStatus *status);

/**
 * Link probe: returns 1 when the library is linked in correctly.
 */
int32_t wxscan_ping(void);

/**
 * Lend this library a decoder for formats it does not carry, or pass NULL to
 * take one back.
 *
 * It is consulted only after the built-in decoders have declined, so it
 * cannot change how a png, jpeg or gif is read. A caller that registers
 * nothing keeps exactly the previous behaviour: unknown bytes come back as
 * `WxScanStatus::UnsupportedFormat`.
 *
 * Register once at start-up. The functions may be called from any thread the
 * caller scans on, and from more than one at a time, so they must be safe to
 * call that way — the system decoders named in this module's documentation
 * all are.
 *
 * # Safety
 * `decoder`, when not NULL, must point to a readable [`WxScanImageDecoder`]
 * whose function pointers, and the `ctx` beside them, stay valid **for the
 * life of the process** — not merely until they are replaced or cleared.
 *
 * Replacing or clearing a registration does not wait for decodes already
 * under way. A decode that has read the slot but not yet called through it
 * will still call the retired pointers with the retired `ctx`, so a host that
 * frees that context, drops a reference the context holds, or unloads the
 * code behind those pointers once this returns has a use-after-free. There is
 * nowhere to put a wait: the alternative is holding the registration lock
 * across the decode, which would serialise every picture in the process
 * behind every other.
 *
 * Registering once at start-up and leaving it, which is what a decoder built
 * into an application does, sidesteps this entirely.
 */
void wxscan_set_image_decoder(const struct WxScanImageDecoder *decoder);

/**
 * Free a result set and everything it owns. Passing NULL is a no-op.
 *
 * # Safety
 * The pointer must come from a scan function of this library and must be freed
 * at most once.
 */
void wxscan_results_free(struct WxScanResults *r);

/**
 * Create a scanner from in-memory model buffers.
 *
 * Passing NULL for both models selects the image-processing-only mode. It
 * still decodes, but the detection rate for small or distant symbols is
 * considerably lower, since that is what the CNN stage contributes.
 *
 * Returns zero if a model fails to load. Release with
 * [`wxscan_scanner_release`].
 *
 * # Safety
 * `detect` and `sr`, when not NULL, must point to at least the corresponding
 * number of readable bytes.
 */
WxScanScannerId wxscan_scanner_new(const uint8_t *detect,
                                   size_t detect_len,
                                   const uint8_t *sr,
                                   size_t sr_len);

/**
 * Set the downscale factor applied before detection.
 *
 * Values outside `(0, 1]` restore the default, which targets a 400x400 area.
 */
void wxscan_scanner_set_scale_factor(WxScanScannerId s, float v);

/**
 * How many scanners are alive in this process.
 *
 * For finding a holder that never gave its handle back. A scanner that is
 * leaked rather than released costs whatever its weights cost for the life of
 * the process, and without this there is no way to see that from outside —
 * which is the usual reason such a leak survives for months.
 *
 * A test can assert this is back where it started; a debug build of an
 * application can watch it across a screen that opens and closes.
 */
size_t wxscan_scanner_count(void);

/**
 * Take a reference to a scanner, returning the same handle for convenience.
 *
 * For a second holder — typically a camera binding handed a scanner the
 * application already owns. It keeps the scanner alive whichever side lets go
 * first. Returns zero, and takes nothing, if the handle names no scanner.
 *
 * Every retain must be matched by a [`wxscan_scanner_release`].
 */
WxScanScannerId wxscan_scanner_retain(WxScanScannerId s);

/**
 * Give up a reference. The scanner is freed when the last holder goes.
 *
 * Releasing a handle that names no scanner — one already released, or never
 * valid — does nothing. It is a bug on the caller's side, and a debug build
 * says so, but it is not one this library can do anything about at that point
 * and it is certainly not a reason to corrupt anything.
 */
void wxscan_scanner_release(WxScanScannerId s);

/**
 * The downscale factor applied before detection, as set by
 * [`wxscan_scanner_set_scale_factor`]. A negative value means the default,
 * which targets a 400x400 area — or that `s` names no scanner.
 */
float wxscan_scanner_scale_factor(WxScanScannerId s);

/**
 * How confident the detector must be to report a candidate, 0.2 by default.
 *
 * Lower recalls more weak symbols along with more false positives; higher does
 * the reverse. Values outside `(0, 1)` are ignored. Without models there is no
 * detector and this does nothing.
 */
void wxscan_scanner_set_confidence_threshold(WxScanScannerId s, float v);

/**
 * The confidence threshold in use, or a negative value when no detector is
 * loaded — or when `s` names no scanner, which is not distinguished here.
 */
float wxscan_scanner_confidence_threshold(WxScanScannerId s);

/**
 * The IoU above which two overlapping candidates are treated as one symbol,
 * 0.45 by default. Values outside `(0, 1)` are ignored.
 */
void wxscan_scanner_set_nms_threshold(WxScanScannerId s, float v);

/**
 * The NMS threshold in use, or a negative value when no detector is loaded —
 * or when `s` names no scanner, which is not distinguished here.
 */
float wxscan_scanner_nms_threshold(WxScanScannerId s);

/**
 * Whether the detector network is loaded. False also for a handle that names
 * no scanner: ask right after taking a reference, when the two cannot be
 * confused.
 */
int32_t wxscan_scanner_has_detector(WxScanScannerId s);

/**
 * Whether the super resolution network is loaded. False also for a handle
 * that names no scanner, as for the detector.
 */
int32_t wxscan_scanner_has_super_resolution(WxScanScannerId s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WXSCAN_H */
