//! C ABI for [`wxscan`], usable from C, C++, Swift, Kotlin, Python and others.
//!
//! The header `include/wxscan.h` is generated by `build.rs` with cbindgen and
//! committed to the repository.
//!
//! Results are returned as plain C structs. Serialization, if a caller needs
//! it, belongs in that caller's binding layer. See [`c_api`] for the entry
//! points and [`results`] for the returned types.
//!
//! The scanner is an explicit handle rather than a global singleton, so several
//! instances can coexist with different models and calls do not contend on one
//! global lock.

mod c_api;
mod results;
mod scanner;

pub use c_api::*;
pub use results::*;
pub use scanner::*;
