//! C ABI for [`wxscan`], usable from C, C++, Swift, Kotlin, Python and others.
//!
//! The header `include/wxscan.h` is generated by `build.rs` with cbindgen and
//! committed to the repository.
//!
//! Results are returned as plain C structs. Serialization, if a caller needs
//! it, belongs in that caller's binding layer. See [`c_api`] for the entry
//! points and [`results`] for the returned types.
//!
//! The scanner is an explicit handle rather than a global singleton, so several
//! instances can coexist with different models and calls do not contend on one
//! global lock.

mod c_api;
// Only wasm has a host to call, so the imports and the `Net` implementation
// are wasm-only; the wire format they agree on is not, and is parsed and
// tested everywhere.
#[cfg(feature = "host-net")]
mod host_net;
// A decoder the host lends for formats this library does not carry. It rides
// with `image-io`, which is what owns the entry points that would consult it.
#[cfg(feature = "image-io")]
mod host_image;
mod results;
mod scanner;

pub use c_api::*;
#[cfg(all(feature = "host-net", target_arch = "wasm32"))]
pub use host_net::*;
#[cfg(feature = "image-io")]
pub use host_image::*;
pub use results::*;
pub use scanner::*;
